version: '3.6'
services:
  api:
    environment:
      - SPRING_PROFILE_ACTIVE=development

  frontend:
    build: 
      target: base
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
